public_repo_path=imgly/starterkit-design-editor-android
public_repo_description=Design Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-design
app_name=Design Editor
package_suffix=design
